# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: S3 Deploy
        # You may pin to the exact commit or the version.
        # uses: Reggionick/s3-deploy@d78e6b5a588e326e4b1afb9b33df2ce28929e5e1
        uses: Reggionick/s3-deploy@v3.1.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        with:
          # Directory to deploy
          folder: /
          # Name of AWS Bucket
          bucket: samjene
          # The destination bucket region
          bucket-region: us-west-2
          # AWS CloudFront distribution ID
          #dist-id: # optional
          # AWS CloudFront invalidation path(s)
          #invalidation: # optional
          # Removes files in S3 that are not available in the local copy of the directory
          #delete-removed: # optional
          # Use this parameter to specify Cache-Control: no-cache, no-store, must-revalidate header
          #no-cache: # optional
          # Upload files with private ACL, needed for S3 static website hosting
          #private: # optional
